### ISSUE TITLE
[Enhancement] Provided pre-build windows binaries

### ISSUE THREAD

**Issue by benbridts** [aws-cloudformation/cloudformation-guard#232]
cfn-guard is hard to use for someone without rust experience on a windows machine

It would be great if there would be a binary that a user can download and run directly

Technically, running inside a lambda could help, but that currently still needs a rust setup, and adds a dependency on an AWS account.

**Comment by akshayrane** [comment]
Hi @benbridts 

As it turns out cfn-guard is available as a binary on Chocolatey and can be installed easily on a Windows machine.

First install chocolatey by following [this installation guide](https://chocolatey.org/install) and then run
````
choco install cloudformation-guard
````

This should install [cfn-guard 2.1](https://community.chocolatey.org/packages/cloudformation-guard) from the package manager as a binary.

HTH,
Akshay | AWS CloudFormation
