### ISSUE TITLE
[GENERAL ISSUE] cfn-guard 2.1 is not installable via crates.io

### ISSUE THREAD

**Issue by benbridts** [aws-cloudformation/cloudformation-guard#257]
The current released version fo cfn-guard is 2.1, but the release available via cargo is 2.0.4. See https://crates.io/crates/cfn-guard

This is also leads to https://github.com/aws-cloudformation/aws-guard-rules-registry/issues/209#issuecomment-1186035090

**Comment by akshayrane** [comment]
Yeah, this is a known issue. We apologize for this discrepancy. We have a dependency on an upstream package called [yaml-rust](https://github.com/chyh1990/yaml-rust) that needs to first address a bug for which we have opened up [a PR]((https://github.com/chyh1990/yaml-rust/pull/180)). Since this update isn't merged and available on crates.io we cannot release our package as well.

We had also added the following disclaimer to the [README](https://github.com/aws-cloudformation/cloudformation-guard#readme) at the time of release.

> **Note:**
> We are excited to release Guard 2.1! We recommend building locally from source code or to install using pre-built binaries. Due to dependencies on [one of the PRs](https://github.com/chyh1990/yaml-rust/pull/180) for [yaml-rust](https://github.com/chyh1990/yaml-rust) library, we are not currently able to publish to various package managers including crates.io.

For issues regarding [aws-guard-rules-registry](https://github.com/aws-cloudformation/aws-guard-rules-registry), request you to open a new issue in the same repository so that it can be tracked to completion.
