### ISSUE TITLE
[Enhancement] Better support for SAM Template Tags

### ISSUE THREAD

**Issue by ajmax** [aws-cloudformation/cloudformation-guard#291]
**Is your feature request related to a problem? Please describe.**

We are attempting to ensure all Serverless Functions have a defined set of tags on them.  We haven't defined any casing requirements, so these tags could be all-caps, lowercase, camel case, etc.

For whatever reason, Tags on serverless functions are [Maps](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html#sam-function-tags) and not a List of Tag objects like on most resources.

This presents a problem, as the "Key" is now the Tag name.  We are unable to right checks like
`Key == /(?i)Application/`

We have tried checking for
`/(?i)Application/ exists` and '/(?i)Application/ !empty', but it appears that the regex doesn't work and it takes the value to literally be /(?i)Application/

**Describe the solution you'd like**
The ability to properly right rules around Tags for Serverless functions, where these Tags are Maps and not Tag objects.  This should also work for Tags applied through Globals.

**Describe alternatives you've considered**

It'd be great if Tags in the serverless framework were Tag objects instead of Maps like everything else, but I realize thats probably not up to you.

**Comment by razcloud** [comment]
Hi @ajmax Thank you for posting this enhancement.  Will discuss with the team and get back to you.

**Comment by joshfried-aws** [comment]
Hi @ajmax thanks for posting. 

After looking into this issue this type of behaviour is currently not supported by CloudFormation-Guard. Currently our only way of supporting this behaviour works when you know exactly how the field is spelled. 

In the future we will look into adding a functionality that would allow for querying the names of keys. 

Thanks

**Comment by joshfried-aws** [comment]
Hi @ajmax I'd like to provide another update here. I seem to have made a mistake in my previous comment. 

I continued to look into this issue and spoke with a teammate of mine. 

we were able to do a check on the key of the tag 

given the following template (I left out most of the template to keep things concise) 

```
AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Resources:
  GuardLambda:
    Type: AWS::Serverless::Function
    Properties:
      Role: yourCustomRoleHere
      Tags:
        firstName: prod
```

we can run the following guard rule with a validate command 

```
let aws_serverless_functions = Resources.*[ Type == 'AWS::Serverless::Function' ]

rule KEY_COMPLIANCE_CHECK when %aws_serverless_functions !empty {
  %aws_serverless_functions.Properties.Tags is_struct
  %aws_serverless_functions.Properties.Tags !empty

  let first_name = %aws_serverless_functions.Properties.Tags[ keys == /^(?i)first([-|_])?name$/ ]

  %first_name !empty
}
```

this rule would pass regardless of the case it was written in. 

I hope this helps. Please let me know if you have any other questions regarding this. 

Thanks

**Comment by hexploder** [comment]
Hi @ajmax

As a workaround to this I transform all SAM resources into normal AWS Cloudformation executing this before checking

```
sam validate --profile $AWS_PROFILE -t ./infraCloudformation.yaml --debug 2>&1 | grep -Pazo '(?s)AWSTemplateFormatVersion.*\n\n' | tr -d '\0' | sed -e '/Key\: lambda\:createdBy\|Value\: SAM/d' > NormalizedCloudformation.yaml
```
_(you dont need the --profile on CodeBuild though)_

This way I transform the CFN with mixed resources into a AWS Cloudformation template, this have some issues that I recently discovered, for example, Api Type events on a Serverless Function doesn't have a AWS Cloudformation version of the resource, and for example APIGateways also have some issues, for example disableExecuteApiEndpoint on a Serverless Api goes on %api.Properties.disableExecuteApiEndpoint but when you translate it, it goes to %api.Properties.Body.x-amazon-apigateway-endpoint-configuration.disableExecuteApiEndpoint and because x-amazon-apigateway-endpoint-configuration has non-alphanumeric characters you have to put in between [""], some issues with that but ensure that all Tags are written the same way.

By the way, the sed -e ... is because SAM Lambda Functions creates an extra Key in position 0 so I needed to erase that.

Hope it helps!

Regards!

**Comment by razcloud** [comment]
Thanks for chiming in @hexploder !!

**Comment by joshfried-aws** [comment]
Hi @ajmax since this issue seems to have been resolved I will close it. 

Feel free to reopen and ask for any clarifications you may like. 

Thanks
