### ISSUE TITLE
Terraform Variable syntax

### ISSUE THREAD

**Issue by mrjeffwagner** [aws-cloudformation/cloudformation-guard#308]
**Describe the issue**
I need the ability to set a variable if a resource type is identified in a Plan file.  I am looking for documentation or information regarding how to write the following line for terraform:

``` let s3_bucket = Resources.*[ Type == "AWS::S3::Bucket" ] ```

**Examples**
Attempted the following:

``` 
let s3_bucket = resource_changes.*[ type == "aws_s3_bucket"]
let s3_bucket = resource_changes[*].*[ type == "aws_s3_bucket"]
let s3_bucket = resource_changes[*].type == "aws_s3_bucket"
```

**Comment by joshfried-aws** [comment]
Hi @mrjeffwagner would you be willing to share an example of your terraform plan, in a json format? 

We cannot provide you a way to query a json file without knowing the structure of the json. 

The reason we start with resources for our CFN templates is because that is the root node, so its our starting point for queries.

**Comment by joshfried-aws** [comment]
Hi @mrjeffwagner I am going to close this issue out for now due to inactivity. Feel free to reopen if you still need help regarding this issue. 

Thanks
