### ISSUE TITLE
[Enhancement] cfn-guard-rulegen for AWS::IAM::Role without a name is missing a rule

### ISSUE THREAD

**Issue by roskelleycj** [aws-cloudformation/cloudformation-guard#61]
**Is your feature request related to a problem? Please describe.**
I have existing templates were the AWS::IAM::Role Name attribute is NOT present, this is because we do not want roles to be named inside the template.  We prefer that CFN generate the name of the role automatically based on the stack AND making it unique, etc.

**Describe the solution you'd like**
I would like to see cfn-guard-rulegen detect that there is no name attribute present and make a rule to NOT allow the name to be defined.  

```
AWS::IAM::Role Name == ''
```
or some such.  Sorry, I'm a bit of a newbie using the tool, and this looked like the only way to express the 'NOT present'

**Describe alternatives you've considered**
Obviously hand coding the rule AFTER cfn-guard-rulegen is executed.  However, that is a bit of a pain on 100+ CFN templates.

**Comment by jotompki** [comment]
Apologies for the delay on this. Right now we don't support key existence checks but it is something we are considering in our next release. I don't think it is something we can account for in rulegen as the tool is not aware of a given resource type's properties; the context for which it defines rules is based on what is in the template. Since role name constraints for the create role api are a minimum length of 1, you could enforce that the name rule as above with a custom message
```
AWS::IAM::Role Name == '' << Role names cannot be specified
```

We are kicking around some null checks in the future (AWS::IAM::Role Name == null) or something like that but for now the above solution should suffice
