### ISSUE TITLE
[Enhancement] Maintain default sort order of result based on input ruleset

### ISSUE THREAD

**Issue by sfarazkazmi** [aws-cloudformation/cloudformation-guard#75]
**Is your feature request related to a problem? Please describe.**
Currently we are alphabetically sorting result which makes it harder to parse the response if you want to pick first error message. It would be ideal if the response follows same order as the input ruleset. 

**Describe the solution you'd like**
Make sorting optional by passing a sort variable
cfn-guard --rule_set --template -s
(-s is for sorted response).

**Describe alternatives you've considered**
An alternate to this could be to allow fail fast and return the first error only. While in most cases customers may want to see all the errors at once, there are cases where only first error is needed.

**Additional context**
None

**Comment by jotompki** [comment]
This should be handled by our proposal #111. Since named rules are specified in the output and output is specified to be JSON, it should be possible to create a rule identifier and see if that specific rule evaluation succeed. In the meantime while we are preparing this release, we don't have plans to sort the rules in the current version of the tooling
