### ISSUE TITLE
How does cfn-guard differentiate from cfn-linter?

### ISSUE THREAD

**Issue by tvb** [aws-cloudformation/cloudformation-guard#9]
Hi AWS,

Awesome news! cfn-guard really looks promising. I do have one question. How does cfn-guard differentiate from cfn-linter (https://github.com/aws-cloudformation/cfn-python-lint)?

**Comment by adamchainz** [comment]
This is also my question. I've written custom cfn-lint rules for compliance. cfn-guard seems to be a faster way of writing such rules. Why isn't it part of cfn-lint?

**Comment by nathanataws** [comment]
We see the two tools as complementary.  As @adamchainz has correctly intuited, cfn-guard is  purpose-built and optimized specifically for the tasks of rule-writing and checking.

**Comment by tvb** [comment]
Hi @nathanataws thank you for replying. Could you elaborate a bit more on this? If you can write rules in cfn-guard, why would one write rules also in cfn-lint?

**Comment by MTNPCGCG** [comment]
Will there be a mechanism for more complex (programmatic rules) as well? For most rules, the rule syntax from cfn-guard is fantastic, but occasionally something more complex might be needed.

**Comment by ranman166** [comment]
So I could assume this is similar to cfn-nag?

**Comment by n1t1nv3rma** [comment]
IMO, this is a great tool for non-programmers to create simple and easy to understand validation rules. 
So one can simply rely on combination of "aws cloudformation validate-template..." CLI and CFN Guard.

**Comment by PatMyron** [comment]
> So one canjust rely on combination of standard AWS CLI "aws cloudformation validate-template..." and CFN Guard.

[`aws cloudformation validate-template`](https://docs.aws.amazon.com/cli/latest/reference/cloudformation/validate-template.html) unfortunately only does very basic validation and does not catch enough

[`cfn-guard`](https://github.com/aws-cloudformation/cloudformation-guard/tree/master/cfn-guard#writing-rules) is focused on faster custom rule writing for concise constraints and doesn't have plans for default rules

[`cfn-lint`](https://github.com/aws-cloudformation/cfn-python-lint/) focuses more on the [default rules](https://github.com/aws-cloudformation/cfn-python-lint/blob/master/docs/rules.md#rules-1) which mostly catch deployment failures since CloudFormation itself doesn't do enough static analysis before provisioning resources
([`cfn-lint`](https://github.com/aws-cloudformation/cfn-python-lint/) has other default rules like not hardcoding sensitive properties/availability zones/partitions/etc, setting [`DeletionPolicy`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-attribute-deletionpolicy.html)/[`UpdateReplacePolicy`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-attribute-updatereplacepolicy.html) to protect certain resources, approaching [template limits](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cloudformation-limits.html), unused [`Parameters`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/parameters-section-structure.html)/[`Mappings`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/mappings-section-structure.html)/[`Conditions`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/conditions-section-structure.html), etc.)

[`cfn_nag`](https://github.com/stelligent/cfn_nag/issues/480)/[`cfripper`](https://github.com/Skyscanner/cfripper) default rules focus more on security

[`cfn-lint`](https://github.com/aws-cloudformation/cfn-python-lint/blob/master/docs/getting_started/rules.md)/[`cfn_nag`](https://github.com/stelligent/cfn_nag/blob/master/custom_rule_development.md)/[`cfripper`](https://cfripper.readthedocs.io/en/latest/rules/#custom-rules) all support more extensible custom rules in addition to their default rules if custom rules aren't expressible within [`cfn-guard`](https://github.com/aws-cloudformation/cloudformation-guard/) concise constraints

**Comment by razcloud** [comment]
Closing this issue as it was a Q&A, and the original question was answered.

For other questions, please create a new Issue.  Thank you.

**Comment by razcloud** [comment]
Closing this issue as it was a Q&A, and the original question was answered.

For other questions, please create a new Issue. Thank you.
